apiVersion: v1
kind: Pod
metadata:
  name: secret-volume-test
spec:
  containers:
  - name: app
    image: nginx
    volumeMounts:
    - name: secret-volume-vol
      mountPath: "/etc/my-secret"
      readOnly: true
  volumes:
  - name: secret-volume-vol
    secret:
      secretName: my-secret