apiVersion: v1

kind: Config

clusters:
- name: k3d-cluster
  cluster:
    server: https://127.0.0.1:6443
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJkekNDQVIyZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQWpNU0V3SHdZRFZRUUREQmhyTTNNdGMyVnkKZG1WeUxXTmhRREUzT0RNMU1UVXpPVE13SGhjTk1qWXdOekE0TVRFMU5qTXpXaGNOTXpZd056QTFNVEUxTmpNegpXakFqTVNFd0h3WURWUVFEREJock0zTXRjMlZ5ZG1WeUxXTmhRREUzT0RNMU1UVXpPVE13V1RBVEJnY3Foa2pPClBRSUJCZ2dxaGtqT1BRTUJCd05DQUFUcnRGZHVURGY0ZXh6clFpYmF5ZUdTVVVVWUp6ZEVwLzVSOTE4NVNoK1oKSW5kUFRxZzlhT0wyUXNYQVd5T2p5R216dE9ENTY2WUZBUHJ2b3dOOThNNEhvMEl3UURBT0JnTlZIUThCQWY4RQpCQU1DQXFRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVUNGL2dJNkNma0FOUzBWMk1EOVMwCmJ4VzRSVlF3Q2dZSUtvWkl6ajBFQXdJRFNBQXdSUUlnR3FSZlA0SDBtKyt4WWg4UTF6VlFzTEFVSHNqOWdaaTIKYzByVjZxSmgzeEVDSVFDUVJkNThoQ0doOS9xUWlWWm9xNmFpRUFWNWZlWUhRc2lqaVdsRklhVW1Bdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K

users:
- name: github-actions
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6InJqbjc2b3QzR2xEY1BwTjhBLUZFQmpEWGRMVTFhMGF2TDZQNFVBQ1FOelkifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzgzNTE5NTY4LCJpYXQiOjE3ODM1MTU5NjgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNDhjZWJmNWYtM2JmNC00NDJhLWE4YzEtYmI2N2Q5ZjRlN2QyIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImdpdGh1Yi1hY3Rpb25zIiwidWlkIjoiMWVhNTRhZWYtMDE5NC00MGI0LTljZmItNjE1MzY0MTM5YzdiIn19LCJuYmYiOjE3ODM1MTU5NjgsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmdpdGh1Yi1hY3Rpb25zIn0.UlaxAZh8yw0KpBoC46YrJMIAfvEVpudPN7mgebgtXNcxJyYZcp33BgRY3xJWdtGk7HKg-NFALdbBIJvdDEt9DCgQGnGLqSP39nV3iMxzic2rb0fE8cdp4YL1ZpSHvTmjatgybq_ApdqN2SlCVzL-j64iqX6aYB3iZ_E0snpit-6Gk778Zv7YXcY9NakNBImM8PQ6Ov30gR79mQcyaG_uUrEH1ww7tvND1DVjsrMknzqNb4gXY61U848b5NJ8JnB3uI6aqFZ0bUtb23-L7bxQxgfWdRbsrT0HOr1Kav-sT5UW5H0Z_aQxzWC4e4RWSNzRyRjAkfsxoV6Ipfc-OssZ5Q

contexts:
- name: github-actions-context
  context:
    cluster: k3d-cluster
    user: github-actions

current-context: github-actions-context